# Generated by Django 5.1.3 on 2024-11-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_alter_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sendwinmail',
            field=models.CharField(default='unsended', max_length=8),
        ),
    ]
